# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[info](sec) npm:"

  # Enable version updates for Ruby
  - package-ecosystem: "bundler"
    # Look for `Ruby Gems` in the following directories 
    directories: 
      - "/"
      - "_plugins"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[info](sec) bundler:"
      
 # Enable version updates for github-actions
  - package-ecosystem: "dotnet-sdk"
    # Look for a `dotnet sdk` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[info](sec) dotnet-sdk:"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
