#gem install jekyll
gem install github-pages
gem install jekyll-avatar
gem install jekyll-coffeescript
gem install jekyll-default-layout
gem install jekyll-github-metadata
gem install jekyll-include-cache
gem install jekyll-mentions
gem install jekyll-optional-front-matter
gem install jekyll-seo-tag
gem install jekyll-sitemap
gem install liquid
gem install minima
gem install nokogiri
gem install jekyll-email-protect
gem install jekyll-google_analytics	
gem install jekyll-last-modified-at
gem install jekyll-maps
gem install jekyll-mentions
gem install jekyll-spaceship
gem install jekyll-tagging
gem install jekyll-toc
gem install json
gem install xml-sitemap
