gem update --system 3.5.17
gem install jekyll
gem install kramdown
gem install rake
gem install json
gem install github-pages
gem install jekyll-avatar
gem install jekyll-coffeescript
#gem install jekyll-commonmark-ghpages
gem install jekyll-default-layout
gem install jekyll-feed
#gem install jekyll-gist
gem install jekyll-github-metadata
#gem install jekyll-include-cache
gem install jekyll-mentions
gem install jekyll-optional-front-matter
#gem install jekyll-relative-links
gem install jekyll-sitemap
gem install liquid
gem install minima
gem install nokogiri
gem install jekyll-email-protect
gem install jekyll-last-modified-at
gem install jekyll-maps
gem install jekyll-mentions
#gem install jekyll-mermaid
gem install jekyll-spaceship
gem install jekyll-tagging
gem install jekyll-toc
gem install jekyll-webmention_io
gem install jekyll-youtube
gem install xml-sitemap
