# [jekyll ](https://rubygems.org/gems/jekyll/versions/4.3.4). Jekyll is a simple, blog aware, static site generator.
    DEFAULTS = {
      # Where things are
      "source"              => Dir.pwd,
      "destination"         => File.join(Dir.pwd, "_site"),
      "collections_dir"     => "",
      "cache_dir"           => ".jekyll-cache",
      "plugins_dir"         => "_plugins",
      "layouts_dir"         => "_layouts",
      "data_dir"            => "_data",
      "includes_dir"        => "_includes",
      "collections"         => {},

      # Handling Reading
      "safe"                => false,
      "include"             => [".htaccess"],
      "exclude"             => [],
      "keep_files"          => [".git", ".svn"],
      "encoding"            => "utf-8",
      "markdown_ext"        => "markdown,mkdown,mkdn,mkd,md",
      "strict_front_matter" => false,

      # Filtering Content
      "show_drafts"         => nil,
      "limit_posts"         => 0,
      "future"              => false,
      "unpublished"         => false,

      # Plugins
      "whitelist"           => [],
      "plugins"             => [],

      # Conversion
      "markdown"            => "kramdown",
      "highlighter"         => "rouge",
      "lsi"                 => false,
      "excerpt_separator"   => "\n\n",
      "incremental"         => false,

      # Serving
      "detach"              => false, # default to not detaching the server
      "port"                => "4000",
      "host"                => "127.0.0.1",
      "baseurl"             => nil, # this mounts at /, i.e. no subdirectory
      "show_dir_listing"    => false,

      # Output Configuration
      "permalink"           => "date",
      "paginate_path"       => "/page:num",
      "timezone"            => nil, # use the local timezone

      "quiet"               => false,
      "verbose"             => false,
      "defaults"            => [],

      "liquid"              => {
        "error_mode"       => "warn",
        "strict_filters"   => false,
        "strict_variables" => false,
      },

      "kramdown"            => {
        "auto_ids"      => true,
        "toc_levels"    => (1..6).to_a,
        "entity_output" => "as_char",
        "smart_quotes"  => "lsquo,rsquo,ldquo,rdquo",
        "input"         => "GFM",
        "hard_wrap"     => false,
        "guess_lang"    => true,
        "footnote_nr"   => 1,
        "show_warnings" => false,
      },
    }.each_with_object(Configuration.new) { |(k, v), hsh| hsh[k] = v.freeze }.freeze

# [jekyll_ai_related_posts](https://rubygems.org/gems/jekyll_ai_related_posts/versions/0.1.3). Populate ai_related_posts using Open AI embeddings
# [jekyll-avatar](https://rubygems.org/gems/jekyll-avatar/versions/0.8.0). A Jekyll plugin for rendering GitHub avatars
# [jekyll-categories](https://rubygems.org/gems/jekyll-categories/versions/0.0.2). Provides a category index page, category pages and category atom feeds for Jekyll.
# [jekyll-coffeescript](https://rubygems.org/gems/jekyll-coffeescript/versions/2.0.0). A CoffeeScript converter for Jekyll.
# [jekyll-commonmark-ghpages](https://rubygems.org/gems/jekyll-commonmark-ghpages/versions/0.4.0). CommonMark generator for Jekyll
# [jekyll-default-layout](https://rubygems.org/gems/jekyll-default-layout/versions/0.1.5). Silently sets default layouts for Jekyll pages and posts
# [jekyll-email-protect](https://rubygems.org/gems/jekyll-email-protect/versions/1.1.0). Email protection liquid filter for Jekyll
# [jekyll-exiftag](https://rubygems.org/gems/jekyll-exiftag/versions/0.1.0). jekyll-exiftag is a LiquidTag Extension for Jekyll to get Exif data from images
# [jekyll-feed](https://rubygems.org/gems/jekyll-feed/versions/0.17.0). A Jekyll plugin to generate an Atom feed of your Jekyll posts
# [jekyll-galleries](https://rubygems.org/gems/jekyll-galleries/versions/0.8.2). Jekyll plugin to automatically generate photo gallery (album) from image folder.
# [jekyll-gist](https://rubygems.org/gems/jekyll-gist/versions/1.5.0). Liquid tag for displaying GitHub Gists in Jekyll sites.
# [jekyll-github-metadata](https://rubygems.org/gems/jekyll-github-metadata/versions/2.16.1). The site.github namespace
# [jekyll-google_analytics](https://rubygems.org/gems/jekyll-google_analytics/versions/0.1.0). Add Google Analytics to your Jekyll site
# [jekyll-include-cache](https://rubygems.org/gems/jekyll-include-cache/versions/0.2.1). A Jekyll plugin to cache the rendering of Liquid includes
# [jekyll-last-modified-at](https://rubygems.org/gems/jekyll-last-modified-at/versions/1.3.2). A liquid tag for Jekyll to indicate the last time a file was modified.
# [jekyll-maps](https://rubygems.org/gems/jekyll-maps/versions/2.4.0). Google Maps support in Jekyll blog to easily embed maps with posts\" locations
# [jekyll-mathjax-csp](https://rubygems.org/gems/jekyll-mathjax-csp/versions/2.0.0). Server-side MathJax rendering for Jekyll with a strict CSP
# [jekyll-mentions](https://rubygems.org/gems/jekyll-mentions/versions/1.6.0). @mention support for your Jekyll site
# [jekyll-mentions](https://rubygems.org/gems/jekyll-mentions/versions/1.6.0). @mention support for your Jekyll site
# [jekyll-menu](https://rubygems.org/gems/jekyll-menu/versions/0.1.1). Easy menu creation with YAML data
# [jekyll-menus](https://rubygems.org/gems/jekyll-menus/versions/0.6.1). Menus (site navigation) for your Jekyll website
# [jekyll-mermaid](https://rubygems.org/gems/jekyll-mermaid/versions/1.0.0). A Jekyll plugin to simplify the creation of mermaid diagrams and flowcharts in your posts and pages.
# [jekyll-nested-menu-generator](https://rubygems.org/gems/jekyll-nested-menu-generator/versions/1.0.1). Provides a tag that generates a nested navigation menu for a specified folder. Useful for automatically generating a multilevel menu that mirrors your directory structure, or generating a menu of generated pages.
# [jekyll-optional-front-matter](https://rubygems.org/gems/jekyll-optional-front-matter/versions/0.3.2). A Jekyll plugin to make front matter optional for Markdown files
# [jekyll-readme-index](https://rubygems.org/gems/jekyll-readme-index/versions/0.3.0). A Jekyll plugin to render a project\"s README as the site\"s index.
# [jekyll-redirect-from](https://rubygems.org/gems/jekyll-redirect-from/versions/0.16.0). Seamlessly specify multiple redirection URLs for your pages and posts
# [jekyll-relative-links](https://rubygems.org/gems/jekyll-relative-links/versions/0.7.0). A Jekyll plugin to convert relative links to markdown files to their rendered equivalents.
# [jekyll-sass-converter](https://rubygems.org/gems/jekyll-sass-converter/versions/3.0.0). A basic Sass converter for Jekyll.
# [jekyll-seo-tag](https://rubygems.org/gems/jekyll-seo-tag/versions/2.8.0). A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site\"s content.
# [jekyll-sitemap](https://rubygems.org/gems/jekyll-sitemap/versions/1.4.0). Automatically generate a sitemap.xml for your Jekyll site.
# [jekyll-spaceship](https://rubygems.org/gems/jekyll-spaceship/versions/0.10.2). A Jekyll plugin to provide powerful supports for table, mathjax, plantuml, mermaid, emoji, video, audio, youtube, vimeo, dailymotion, spotify, soundcloud, etc.
# [jekyll-swiss](https://rubygems.org/gems/jekyll-swiss/versions/1.0.0). A bold typographic theme for Jekyll, inspired by Swiss design.
# [jekyll-tagging](https://rubygems.org/gems/jekyll-tagging/versions/1.1.0). Jekyll plugin to automatically generate a tag cloud and tag pages.
# [jekyll-theme-conference](https://rubygems.org/gems/jekyll-theme-conference/versions/3.6.5). Jekyll template for a conference website containing program, speaker, talks and room overview.
# [jekyll-titles-from-headings](https://rubygems.org/gems/jekyll-titles-from-headings/versions/0.5.3). A Jekyll plugin to pull the page title from the first Markdown heading when none is specified.
# [jekyll-toc](https://rubygems.org/gems/jekyll-toc/versions/0.19.0). Jekyll (Ruby static website generator) plugin which generates a Table of Contents for the page.
# [jekyll-webmention_io](https://rubygems.org/gems/jekyll-webmention_io/versions/4.0.0). This Gem includes a suite of tools for managing webmentions in Jekyll: * Tags * Count of webmentions (filterable) * All webmentions (filterable) * Bookmarks * Likes * Links * Posts * Replies * Reposts * RSVPs * Contents for the `head` of your pages * JavaScript enhancements * Commands - Send webmentions you’ve made * Generators - Collect webmentions from Webmention.io and gather sites you’ve mentioned
# [jekyll-youtube](https://rubygems.org/gems/jekyll-youtube/versions/1.0.0). jekyll plugin to generate html snippets for embedding Youtube videos
# [json](https://rubygems.org/gems/json/versions/2.7.2). This is a JSON implementation as a Ruby extension in C.	|
# [kramdown-converter-pdf](https://rubygems.org/gems/kramdown-converter-pdf/versions/1.0.6). kramdown-converter-pdf uses Prawn to convert a kramdown document to PDF
# [kramdown-parser-gfm](https://rubygems.org/gems/kramdown-parser-gfm/versions/1.1.0). kramdown-parser-gfm provides a kramdown parser for the GFM dialect of Markdown
# [kramdown-parser-gfm](https://rubygems.org/gems/kramdown-parser-gfm/versions/1.1.0). kramdown-parser-gfm provides a kramdown parser for the GFM dialect of Markdown
# [kramdown-rfc2629](https://rubygems.org/gems/kramdown-rfc2629/versions/1.7.18). An RFCXML (RFC 799x) generating backend for Thomas Leitner\"s "kramdown" markdown parser. Mostly useful for RFC writers.
# [kramdown](https://rubygems.org/gems/kramdown/versions/2.4.0). kramdown is yet-another-markdown-parser but fast, pure Ruby, using a strict syntax definition and supporting several common extensions.
# [kramdown](https://rubygems.org/gems/kramdown/versions/2.4.0). kramdown is yet-another-markdown-parser but fast, pure Ruby, using a strict syntax definition and supporting several common extensions.
# [liquid](https://rubygems.org/gems/liquid/versions/5.5.1). A secure, non-evaling end user template engine with aesthetic markup.
# [logger](https://rubygems.org/gems/logger/versions/1.6.0). Provides a simple logging utility for outputting messages.
# [mathjax-rails](https://rubygems.org/gems/mathjax-rails/versions/2.6.1). This
# [mathjax-renderer](https://rubygems.org/gems/mathjax-renderer/versions/0.0.9). In case there is a need to pre-render MathJax expressions or insert as images
# [mathjax-yard](https://rubygems.org/gems/mathjax-yard/versions/1.0.3). mathjax-yard provides mathjax extention to yard.
# [mathjax_rails](https://rubygems.org/gems/mathjax_rails/versions/0.0.1). A Ruby
# [minima](https://rubygems.org/gems/minima/versions/2.5.2). A beautiful, minimal theme for Jekyll.
# [minitest](https://rubygems.org/gems/minitest/versions/5.24.1). minitest provides a complete suite of testing facilities supporting TDD, BDD, mocking, and benchmarking.
# [net-http](https://rubygems.org/gems/net-http/versions/0.4.1). HTTP client api for Ruby.
# [nokogiri](https://rubygems.org/gems/nokogiri/versions/1.16.7-x86_64-linux). Nokogiri (鋸) makes it easy and painless to work with XML and HTML from Ruby. It provides a sensible, easy-to-understand API for reading, writing, modifying, and querying documents. It is fast and standards-compliant by relying on native parsers like libxml2, libgumbo, or xerces.
# [rake](https://rubygems.org/gems/rake/versions/13.2.1). Rake is a Make-like program implemented in Ruby. Tasks and dependencies are specified in standard Ruby syntax.
# [rexml](https://rubygems.org/gems/rexml/versions/3.3.4). An XML toolkit for Rub
# [rouge](https://rubygems.org/gems/rouge/versions/4.3.0). Rouge aims to a be a simple, easy-to-extend drop-in replacement for pygments.
# [safe_yaml](https://rubygems.org/gems/safe_yaml/versions/1.0.5). Parse YAML safely
# [sass-embedded](https://rubygems.org/gems/sass-embedded/versions/1.77.8). A Ruby library that will communicate with Embedded Dart Sass using the Embedded Sass protocol.
# [sassc-embedded](https://rubygems.org/gems/sassc-embedded/versions/1.78.0). An embedded sass shim for SassC.
# [simpleidn](https://rubygems.org/gems/simpleidn/versions/0.2.3). This
# [social_linker](https://rubygems.org/gems/social_linker/versions/0.5.0.1). Social linker generates share-links for the different social networks from a simple SocialLinker::Subject class. Supported networks are: Twitter, Facebook, LinkedIn, Google+, Pinterest, and email
# [uri](https://rubygems.org/gems/uri/versions/0.13.0). URI is a module providing classes to handle Uniform Resource Identifiers
# [xml-sitemap](https://rubygems.org/gems/xml-sitemap/versions/1.3.3). Provides a wrapper to generate XML sitemaps and sitemap indexes. 


exclude:
  # Jekyll 
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

