# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics — Discussions
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 4 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  #push: {branches: ["_staging", "main", "master"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write

    steps:
        - name: GitHub Discussions
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.discussions.svg
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_discussions: yes
            plugin_discussions_categories_limit: 8
