# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: followerup.yml —  Metrics — Follow-ups
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 5 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  #push: {branches: ["_staging", "main", "master"]}
permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write

    steps:
        - name: Harden Runner
          uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
          with:
            egress-policy: audit

        - name: Opened on user's repositories
          uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # latest
          with:
            filename: metrics.plugin.followup.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_followup: yes
        
        - name: Opened by user
          uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # latest
          with:
            filename: metrics.plugin.followup.user.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_followup: yes
            plugin_followup_sections: user
        
        - name: Indepth analysis
          uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # latest
          with:
            filename: metrics.plugin.followup.indepth.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_followup: yes
            plugin_followup_indepth: yes
        
        - name: Exclude Archived
          uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # latest
          with:
            filename: metrics.plugin.followup.archived.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            base: ""
            plugin_followup: yes
            plugin_followup_archived: no
          
