on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release 
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          pull-request-header: New release created for the following reasons
          package-name: release-please-action
      - name: Changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
           command: manifest
      - name: "Build Changelog"
