# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: stargazers.yml — Metrics — Stargazers
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "45 23 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  #push: {branches: ["_staging", "main", "master"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write

    steps: 
        - name: Stargazers Using classic charts
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.stargazers.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_stargazers: yes
        
        - name: Stargazers Using graph charts
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.stargazers.graph.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_stargazers: yes
            plugin_stargazers_charts_type: graph
        
        - name: Stargazers With worldmap
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.stargazers.worldmap.svg
            use_prebuilt_image: yes
            token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
            template: markdown
            base: ""
            plugin_stargazers: yes
            plugin_stargazers_charts: no
            plugin_stargazers_worldmap: yes
            plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
            plugin_stargazers_worldmap_sample: 200
